caddy_version: 2.7.6
cluster_agent_version: 1.8.1
hardware_discovery_agent_version: 1.7.1
in_band_manageability_version: 1.0.2
node_agent_version: 1.8.1
platform_manageability_agent_version: 0.2.2
platform_observability_agent_version: 1.10.1
platform_telemetry_agent_version: 1.5.2
platform_update_agent_version: 1.7.3
