# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: enic
description: Edge Node in a Container
type: application
version: 0.8.12
appVersion: "0.8.12"
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
