---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Scorecard CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-scorecard:
    permissions:
      security-events: write   # required for SARIF upload
      id-token: write
      contents: read

    uses: open-edge-platform/orch-ci/.github/workflows/post-merge-scorecard.yml@263c6ab72c1ca39167eacfe8480bd96eff59b912  # v0.1.69
    with:
      project_folder: "."
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
